version: '2'

services:

    opengrok:
        image: iwa-na/opengrok
        ports:
            - "8080:8080"
        volumes:
            - /srv/docker/opengrok/tomcat/conf:/tomcat/conf
            - /srv/docker/opengrok/opengrok:/var/opengrok
            - /var/opengrok/src:/var/opengrok/src
